=== oshToy/Character-Aware-LM-WER/json_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "logs_folder": {
      "type": "string"
    },
    "data_sets_folder": {
      "type": "string"
    },
    "trained_models_folder": {
      "type": "string"
    },

    "models": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "data_set": {
              "type": "string"
            },
            "training": {
              "type": "boolean"
            },
             "testing": {
              "type": "boolean"
            },
            "checkpoint_number_for_train_or_null_for_last_checkpoint": {
              "type": ["integer", "null"]
            },

            "checkpoint_file_for_test": {
              "type": ["string", "null"]
            },

            "embedding": {
              "type": "array"
            },
            "fasttext_model_path": {
              "type": "string"
            }
          },
          "required": [
            "data_set",
            "training",
            "testing",
            "checkpoint_number_for_test_or_null_for_last_checkpoint",
            "checkpoint_file_for_test",
            "embedding",
            "fasttext_model_path"
          ]
        }
      ]
    }
  },
  "required": [
    "logs_folder",
    "data_sets_folder",
    "trained_models_folder",
    "models"
  ]
}

=== oshToy/Character-Aware-LM-WER/config - example.json
{
"logs_folder":"./logs/",
"data_sets_folder":"./data_sets",
"trained_models_folder":"./trained_models",
"models":[{
 "data_set": "PeenTreeBank",
 "training": true,
 "testing": false,
 "checkpoint_number_for_test_or_null_for_last_checkpoint": null,
  "checkpoint_file_for_test": null,
 "embedding":[
  "kim"
 ]
}
]
}

=== oshToy/Character-Aware-LM-WER/config.json
{
"logs_folder":"./logs/",
"data_sets_folder":"E://data_sets/",
"trained_models_folder":"./trained_models_wer",
"models":[{
 "data_set": "AMI",
 "training": false,
 "testing": true,
 "checkpoint_number_for_test_or_null_for_last_checkpoint": null,
 "checkpoint_file_for_test": "C:\\Users\\Ohad.Volk\\Desktop\\Oshri\\tf-lstm-char-cnn-master\\tf-lstm-char-cnn-master\\trained_models_wer\\AMI_2020-04-12--23-10-25\\epoch008_4813.5529.model",
 "embedding": "kim fasttext",
 "fasttext_model_path": "E:\\RNNLM Project\\Models\\Wikipedia\\Lower Case\\15 Epoch\\Wikipedia_epoch15.model"
}
]
}
